<?php

namespace App\Imports;

use App\Models\User;
use App\Models\Questioner;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\SkipsFailures;
use Maatwebsite\Excel\Concerns\SkipsOnFailure;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;

class MhsQuestionerImport implements ToModel, WithHeadingRow, WithValidation, SkipsOnFailure
{
    use SkipsFailures;
    
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        // If nim exists, proceed with the insert
        return Questioner::updateOrCreate(
            ['user_id' => $row['user_id']],
            [
                'a_1' => $row['a_1'],
                'a_2' => $row['a_2'],
                'a_3' => $row['a_3'],
                'a_4' => $row['a_4'],
                'a_5' => $row['a_5'],
                'a_6' => $row['a_6'],
                'a_7' => $row['a_7'],
                'a_8' => $row['a_8'],
                'a_9' => $row['a_9'],
                'a_10' => $row['a_10'],
                'a_11' => $row['a_11'],
                'a_12' => $row['a_12'],
                'a_13' => $row['a_13'],
                'a_14' => $row['a_14'],
                'a_15' => $row['a_15'],
                'a_16' => $row['a_16'],
                'a_17' => $row['a_17'],
                'a_18' => $row['a_18'],
                'b_1' => $row['b_1'],
                'b_2' => $row['b_2'],
                'b_3' => $row['b_3'],
                'b_4' => $row['b_4'],
                'b_5' => $row['b_5'],
                'b_6' => $row['b_6'],
                'b_7' => $row['b_7'],
                'b_8' => $row['b_8'],
                'b_9' => $row['b_9'],
                'b_10' => $row['b_10'],
                'b_11' => $row['b_11'],
                'b_12' => $row['b_12'],
                'b_13' => $row['b_13'],
                'b_14' => $row['b_14'],
                'b_15' => $row['b_15'],
                'b_16' => $row['b_16'],
                'b_17' => $row['b_17'],
                'b_18' => $row['b_18'],
                'c_1' => $row['c_1'],
                'd_1' => $row['d_1'],
                'd_2' => $row['d_2'],
                'd_3' => $row['d_3'],
                'd_4' => $row['d_4'],
                'd_5' => $row['d_5'],
                'e_1' => $row['e_1'],
                'e_2' => $row['e_2'],
                'e_3' => $row['e_3'],
                'e_4' => $row['e_4'],
                'e_5' => $row['e_5'],
                'f_1' => $row['f_1'],
                'f_2' => $row['f_2'],
                'f_3' => $row['f_3'],
                'f_4' => $row['f_4'],
                'f_5' => $row['f_5'],
                'f_6' => $row['f_6'],
                'f_7' => $row['f_7'],
                'f_8' => $row['f_8'],
                'f_9' => $row['f_9'],
                'f_10' => $row['f_10'],
                'g_1' => $row['g_1'],
                'g_2' => $row['g_2'],
                'g_3' => $row['g_3'],
                'g_4' => $row['g_4'],
                'g_5' => $row['g_5'],
                'g_6' => $row['g_6'],
                'h_1' => $row['h_1'],
                'i_1' => $row['i_1'],
                'j_1' => $row['j_1'],
            ]
        );
    }

    public function rules(): array
    {
        return [
            'nim' => 'required|exists:users,nim',
            'a_1' => 'required|in:0,1,2,3,4|integer',
            'a_2' => 'required|in:0,1,2,3,4|integer',
            'a_3' => 'required|in:0,1,2,3,4|integer',
            'a_4' => 'required|in:0,1,2,3,4|integer',
            'a_5' => 'required|in:0,1,2,3,4|integer',
            'a_6' => 'required|in:0,1,2,3,4|integer',
            'a_7' => 'required|in:0,1,2,3,4|integer',
            'a_8' => 'required|in:0,1,2,3,4|integer',
            'a_9' => 'required|in:0,1,2,3,4|integer',
            'a_10' => 'required|in:0,1,2,3,4|integer',
            'a_11' => 'required|in:0,1,2,3,4|integer',
            'a_12' => 'required|in:0,1,2,3,4|integer',
            'a_13' => 'required|in:0,1,2,3,4|integer',
            'a_14' => 'required|in:0,1,2,3,4|integer',
            'a_15' => 'required|in:0,1,2,3,4|integer',
            'a_16' => 'required|in:0,1,2,3,4|integer',
            'a_17' => 'required|in:0,1,2,3,4|integer',
            'a_18' => 'required|in:0,1,2,3,4|integer',
            'b_1' => 'required|in:0,1,2,3,4|integer',
            'b_2' => 'required|in:0,1,2,3,4|integer',
            'b_3' => 'required|in:0,1,2,3,4|integer',
            'b_4' => 'required|in:0,1,2,3,4|integer',
            'b_5' => 'required|in:0,1,2,3,4|integer',
            'b_6' => 'required|in:0,1,2,3,4|integer',
            'b_7' => 'required|in:0,1,2,3,4|integer',
            'b_8' => 'required|in:0,1,2,3,4|integer',
            'b_9' => 'required|in:0,1,2,3,4|integer',
            'b_10' => 'required|in:0,1,2,3,4|integer',
            'b_11' => 'required|in:0,1,2,3,4|integer',
            'b_12' => 'required|in:0,1,2,3,4|integer',
            'b_13' => 'required|in:0,1,2,3,4|integer',
            'b_14' => 'required|in:0,1,2,3,4|integer',
            'b_15' => 'required|in:0,1,2,3,4|integer',
            'b_16' => 'required|in:0,1,2,3,4|integer',
            'b_17' => 'required|in:0,1,2,3,4|integer',
            'b_18' => 'required|in:0,1,2,3,4|integer',
            'c_1' => 'required|in:0,1,2,3,4|integer',
            'd_1' => 'required|in:0,1,2,3,4|integer',
            'd_2' => 'required|in:0,1,2,3,4|integer',
            'd_3' => 'required|in:0,1,2,3,4|integer',
            'd_4' => 'required|in:0,1,2,3,4|integer',
            'd_5' => 'required|in:0,1,2,3,4|integer',
            'e_1' => 'required|in:0,1,2,3,4|integer',
            'e_2' => 'required|in:0,1,2,3,4|integer',
            'e_3' => 'required|in:0,1,2,3,4|integer',
            'e_4' => 'required|in:0,1,2,3,4|integer',
            'e_5' => 'required|in:0,1,2,3,4|integer',
            'f_1' => 'required|in:0,1,2,3,4|integer',
            'f_2' => 'required|in:0,1,2,3,4|integer',
            'f_3' => 'required|in:0,1,2,3,4|integer',
            'f_4' => 'required|in:0,1,2,3,4|integer',
            'f_5' => 'required|in:0,1,2,3,4|integer',
            'f_6' => 'required|in:0,1,2,3,4|integer',
            'f_7' => 'required|in:0,1,2,3,4|integer',
            'f_8' => 'required|in:0,1,2,3,4|integer',
            'f_9' => 'required|in:0,1,2,3,4|integer',
            'f_10' => 'required|in:0,1,2,3,4|integer',
            'g_1' => 'required|in:0,1,2,3,4|integer',
            'g_2' => 'required|in:0,1,2,3,4|integer',
            'g_3' => 'required|in:0,1,2,3,4|integer',
            'g_4' => 'required|in:0,1,2,3,4|integer',
            'g_5' => 'required|in:0,1,2,3,4|integer',
            'g_6' => 'required|in:0,1,2,3,4|integer',
            'h_1' => 'required|string|max:255',
            'i_1' => 'required|string|max:255',
            'j_1' => 'required|string|max:255',
        ];
    }

    public function customValidationMessages()
    {
        return [
            'nim.required' => 'NIM diperlukan.',
            'nim.exists' => 'NIM tidak ditemukan.',
            'a_1.required' => 'Kolom a_1 diperlukan.',
            'a_1.in' => 'Kolom a_1 harus berupa angka antara 0 dan 4.',
            'a_2.required' => 'Kolom a_2 diperlukan.',
            'a_2.in' => 'Kolom a_2 harus berupa angka antara 0 dan 4.',
            'a_3.required' => 'Kolom a_3 diperlukan.',
            'a_3.in' => 'Kolom a_3 harus berupa angka antara 0 dan 4.',
            'a_4.required' => 'Kolom a_4 diperlukan.',
            'a_4.in' => 'Kolom a_4 harus berupa angka antara 0 dan 4.',
            'a_5.required' => 'Kolom a_5 diperlukan.',
            'a_5.in' => 'Kolom a_5 harus berupa angka antara 0 dan 4.',
            'a_6.required' => 'Kolom a_6 diperlukan.',
            'a_6.in' => 'Kolom a_6 harus berupa angka antara 0 dan 4.',
            'a_7.required' => 'Kolom a_7 diperlukan.',
            'a_7.in' => 'Kolom a_7 harus berupa angka antara 0 dan 4.',
            'a_8.required' => 'Kolom a_8 diperlukan.',
            'a_8.in' => 'Kolom a_8 harus berupa angka antara 0 dan 4.',
            'a_9.required' => 'Kolom a_9 diperlukan.',
            'a_9.in' => 'Kolom a_9 harus berupa angka antara 0 dan 4.',
            'a_10.required' => 'Kolom a_10 diperlukan.',
            'a_10.in' => 'Kolom a_10 harus berupa angka antara 0 dan 4.',
            'a_11.required' => 'Kolom a_11 diperlukan.',
            'a_11.in' => 'Kolom a_11 harus berupa angka antara 0 dan 4.',
            'a_12.required' => 'Kolom a_12 diperlukan.',
            'a_12.in' => 'Kolom a_12 harus berupa angka antara 0 dan 4.',
            'a_13.required' => 'Kolom a_13 diperlukan.',
            'a_13.in' => 'Kolom a_13 harus berupa angka antara 0 dan 4.',
            'a_14.required' => 'Kolom a_14 diperlukan.',
            'a_14.in' => 'Kolom a_14 harus berupa angka antara 0 dan 4.',
            'a_15.required' => 'Kolom a_15 diperlukan.',
            'a_15.in' => 'Kolom a_15 harus berupa angka antara 0 dan 4.',
            'a_16.required' => 'Kolom a_16 diperlukan.',
            'a_16.in' => 'Kolom a_16 harus berupa angka antara 0 dan 4.',
            'a_17.required' => 'Kolom a_17 diperlukan.',
            'a_17.in' => 'Kolom a_17 harus berupa angka antara 0 dan 4.',
            'a_18.required' => 'Kolom a_18 diperlukan.',
            'a_18.in' => 'Kolom a_18 harus berupa angka antara 0 dan 4.',
            'b_1.required' => 'Kolom b_1 diperlukan.',
            'b_1.in' => 'Kolom b_1 harus berupa angka antara 0 dan 4.',
            'b_2.required' => 'Kolom b_2 diperlukan.',
            'b_2.in' => 'Kolom b_2 harus berupa angka antara 0 dan 4.',
            'b_3.required' => 'Kolom b_3 diperlukan.',
            'b_3.in' => 'Kolom b_3 harus berupa angka antara 0 dan 4.',
            'b_4.required' => 'Kolom b_4 diperlukan.',
            'b_4.in' => 'Kolom b_4 harus berupa angka antara 0 dan 4.',
            'b_5.required' => 'Kolom b_5 diperlukan.',
            'b_5.in' => 'Kolom b_5 harus berupa angka antara 0 dan 4.',
            'b_6.required' => 'Kolom b_6 diperlukan.',
            'b_6.in' => 'Kolom b_6 harus berupa angka antara 0 dan 4.',
            'b_7.required' => 'Kolom b_7 diperlukan.',
            'b_7.in' => 'Kolom b_7 harus berupa angka antara 0 dan 4.',
            'b_8.required' => 'Kolom b_8 diperlukan.',
            'b_8.in' => 'Kolom b_8 harus berupa angka antara 0 dan 4.',
            'b_9.required' => 'Kolom b_9 diperlukan.',
            'b_9.in' => 'Kolom b_9 harus berupa angka antara 0 dan 4.',
            'b_10.required' => 'Kolom b_10 diperlukan.',
            'b_10.in' => 'Kolom b_10 harus berupa angka antara 0 dan 4.',
            'b_11.required' => 'Kolom b_11 diperlukan.',
            'b_11.in' => 'Kolom b_11 harus berupa angka antara 0 dan 4.',
            'b_12.required' => 'Kolom b_12 diperlukan.',
            'b_12.in' => 'Kolom b_12 harus berupa angka antara 0 dan 4.',
            'b_13.required' => 'Kolom b_13 diperlukan.',
            'b_13.in' => 'Kolom b_13 harus berupa angka antara 0 dan 4.',
            'b_14.required' => 'Kolom b_14 diperlukan.',
            'b_14.in' => 'Kolom b_14 harus berupa angka antara 0 dan 4.',
            'b_15.required' => 'Kolom b_15 diperlukan.',
            'b_15.in' => 'Kolom b_15 harus berupa angka antara 0 dan 4.',
            'b_16.required' => 'Kolom b_16 diperlukan.',
            'b_16.in' => 'Kolom b_16 harus berupa angka antara 0 dan 4.',
            'b_17.required' => 'Kolom b_17 diperlukan.',
            'b_17.in' => 'Kolom b_17 harus berupa angka antara 0 dan 4.',
            'b_18.required' => 'Kolom b_18 diperlukan.',
            'b_18.in' => 'Kolom b_18 harus berupa angka antara 0 dan 4.',
            'c_1.required' => 'Kolom c_1 diperlukan.',
            'c_1.in' => 'Kolom c_1 harus berupa angka antara 0 dan 4.',
            'd_1.required' => 'Kolom d_1 diperlukan.',
            'd_1.in' => 'Kolom d_1 harus berupa angka antara 0 dan 4.',
            'd_2.required' => 'Kolom d_2 diperlukan.',
            'd_2.in' => 'Kolom d_2 harus berupa angka antara 0 dan 4.',
            'd_3.required' => 'Kolom d_3 diperlukan.',
            'd_3.in' => 'Kolom d_3 harus berupa angka antara 0 dan 4.',
            'd_4.required' => 'Kolom d_4 diperlukan.',
            'd_4.in' => 'Kolom d_4 harus berupa angka antara 0 dan 4.',
            'd_5.required' => 'Kolom d_5 diperlukan.',
            'd_5.in' => 'Kolom d_5 harus berupa angka antara 0 dan 4.',
            'e_1.required' => 'Kolom e_1 diperlukan.',
            'e_1.in' => 'Kolom e_1 harus berupa angka antara 0 dan 4.',
            'e_2.required' => 'Kolom e_2 diperlukan.',
            'e_2.in' => 'Kolom e_2 harus berupa angka antara 0 dan 4.',
            'e_3.required' => 'Kolom e_3 diperlukan.',
            'e_3.in' => 'Kolom e_3 harus berupa angka antara 0 dan 4.',
            'e_4.required' => 'Kolom e_4 diperlukan.',
            'e_4.in' => 'Kolom e_4 harus berupa angka antara 0 dan 4.',
            'e_5.required' => 'Kolom e_5 diperlukan.',
            'e_5.in' => 'Kolom e_5 harus berupa angka antara 0 dan 4.',
            'f_1.required' => 'Kolom f_1 diperlukan.',
            'f_1.in' => 'Kolom f_1 harus berupa angka antara 0 dan 4.',
            'f_2.required' => 'Kolom f_2 diperlukan.',
            'f_2.in' => 'Kolom f_2 harus berupa angka antara 0 dan 4.',
            'f_3.required' => 'Kolom f_3 diperlukan.',
            'f_3.in' => 'Kolom f_3 harus berupa angka antara 0 dan 4.',
            'f_4.required' => 'Kolom f_4 diperlukan.',
            'f_4.in' => 'Kolom f_4 harus berupa angka antara 0 dan 4.',
            'f_5.required' => 'Kolom f_5 diperlukan.',
            'f_5.in' => 'Kolom f_5 harus berupa angka antara 0 dan 4.',
            'f_6.required' => 'Kolom f_6 diperlukan.',
            'f_6.in' => 'Kolom f_6 harus berupa angka antara 0 dan 4.',
            'f_7.required' => 'Kolom f_7 diperlukan.',
            'f_7.in' => 'Kolom f_7 harus berupa angka antara 0 dan 4.',
            'f_8.required' => 'Kolom f_8 diperlukan.',
            'f_8.in' => 'Kolom f_8 harus berupa angka antara 0 dan 4.',
            'f_9.required' => 'Kolom f_9 diperlukan.',
            'f_9.in' => 'Kolom f_9 harus berupa angka antara 0 dan 4.',
            'f_10.required' => 'Kolom f_10 diperlukan.',
            'f_10.in' => 'Kolom f_10 harus berupa angka antara 0 dan 4.',
            'g_1.required' => 'Kolom g_1 diperlukan.',
            'g_1.in' => 'Kolom g_1 harus berupa angka antara 0 dan 4.',
            'g_2.required' => 'Kolom g_2 diperlukan.',
            'g_2.in' => 'Kolom g_2 harus berupa angka antara 0 dan 4.',
            'g_3.required' => 'Kolom g_3 diperlukan.',
            'g_3.in' => 'Kolom g_3 harus berupa angka antara 0 dan 4.',
            'g_4.required' => 'Kolom g_4 diperlukan.',
            'g_4.in' => 'Kolom g_4 harus berupa angka antara 0 dan 4.',
            'g_5.required' => 'Kolom g_5 diperlukan.',
            'g_5.in' => 'Kolom g_5 harus berupa angka antara 0 dan 4.',
            'g_6.required' => 'Kolom g_6 diperlukan.',
            'g_6.in' => 'Kolom g_6 harus berupa angka antara 0 dan 4.',
            'h_1.required' => 'Kolom h_1 diperlukan.',
            'h_1.string' => 'Kolom h_1 harus berupa string.',
            'h_1.max' => 'Kolom h_1 tidak boleh lebih dari 255 karakter.',
            'i_1.required' => 'Kolom i_1 diperlukan.',
            'i_1.string' => 'Kolom i_1 harus berupa string.',
            'i_1.max' => 'Kolom i_1 tidak boleh lebih dari 255 karakter.',
            'j_1.required' => 'Kolom j_1 diperlukan.',
            'j_1.string' => 'Kolom j_1 harus berupa string.',
            'j_1.max' => 'Kolom j_1 tidak boleh lebih dari 255 karakter.',
        ];
    }

    public function prepareForValidation($row)
    {
        // Trim all fields
        $row = array_map('trim', $row);

        // fetch and get user id from the nim at $row['nim']
        $user = User::where('nim', $row['nim'])->first();
        if ($user) {
            $row['user_id'] = $user->id;
        }

        return $row;
    }
}
